### ISSUE TITLE
关于用户管理的小问题

### ISSUE THREAD

**Issue by calfzhou** [wikilab/dev-wiki#1]
看到技术架构中提到

> API 封装数据库，对外统一提供 RESTful 接口。网站端关注展现部分，所有数据均通过 API 进行读取。

想问一下，API和网站是两个独立的应用吗？网站里用户的登录和注册功能，是怎么跟API协调的呢？

多谢！

**Comment by luin** [comment]
使用 xauth。网站通过用户名密码向 API 申请 token 并存入 session。

**Comment by calfzhou** [comment]
好的，我看下。我之前一个项目（用Ruby on Rails写的），是直接把API和主网站写在一起了，二者都直接访问数据库。其他的应用没有用户登录，只有授权，就都走API了。

现在要做一个新的项目，想把API和主网站也都分开。API用的是OAuth 2.0授权，这样就要在API那边启用password方式的授权吧？

**Comment by luin** [comment]
对没错

**Comment by calfzhou** [comment]
cool, 多谢，有问题再来讨教！

**Comment by calfzhou** [comment]
还有个小问题想问一下，如果想提供第三方授权登录，相关的逻辑是写在api层还是只要写在web网站里就可以呢？

**Comment by luin** [comment]
写在 api 层

**Comment by calfzhou** [comment]
好，多谢！

**Comment by calfzhou** [comment]
再打扰一下，呵呵，如果这样架构的网站+API要对外提供oauth授权，那么第三方网站要申请授权的时候，相应的用户登录和确认授权页面是做在API里面，还是做在web网站中，然后web网站再向API转发相应的请求？

**Comment by luin** [comment]
都做在API里，web和其他第三方客户端的地位是一样的，可以看做web就是API的一个客户端

**Comment by calfzhou** [comment]
那就是在API里也要有最基本的登录和确认授权的页面咯？就是authorization server的部分

**Comment by luin** [comment]
对的

**Comment by calfzhou** [comment]
好，多谢多谢！
